class CreateEvaluations < ActiveRecord::Migration[7.2]
  def change
    create_table :evaluations do |t|
      t.timestamps
      t.string "form_key", null: false
      t.string "teams_organized_based_on_platform_technology", null: false, default: "unchecked"
      t.string "defined_and_documented_process", null: false, default: "unchecked"
      t.string "one_backlog_per_team", null: false, default: "unchecked"
      t.string "adopt_agile_methodologies", null: false, default: "unchecked"
      t.string "remove_team_boundaries", null: false, default: "unchecked"
      t.string "extended_team_collaboration", null: false, default: "unchecked"
      t.string "remove_boundary_dev_ops", null: false, default: "unchecked"
      t.string "common_process_for_all_changes", null: false, default: "unchecked"
      t.string "cross_team_continuous_improvement", null: false, default: "unchecked"
      t.string "teams_responsible_all_the_way_to_production", null: false, default: "unchecked"
      t.string "cross_functional_teams", null: false, default: "unchecked"
      t.string "centralized_version_control", null: false, default: "unchecked"
      t.string "automated_build_scripts", null: false, default: "unchecked"
      t.string "no_management_of_artifacts", null: false, default: "unchecked"
      t.string "manual_deployment", null: false, default: "unchecked"
      t.string "environments_are_manually_provisioned", null: false, default: "unchecked"
      t.string "polling_ci_builds", null: false, default: "unchecked"
      t.string "any_build_can_be_re_created_from_source_control", null: false, default: "unchecked"
      t.string "management_of_build_artifacts", null: false, default: "unchecked"
      t.string "automated_deployment_scripts", null: false, default: "unchecked"
      t.string "automated_provisioning_of_environments", null: false, default: "unchecked"
      t.string "commit_hook_ci_builds", null: false, default: "unchecked"
      t.string "build_fails_if_quality_is_not_met_code_analysis_performance_etc", null: false, default: "unchecked"
      t.string "push_button_deployment_and_release_of_any_releasable_artifact_to_any_environment", null: false, default: "unchecked"
      t.string "standard_deployment_process_for_all_environments", null: false, default: "unchecked"
      t.string "team_priorities_keeping_codebase_deployable_over_doing_new_work", null: false, default: "unchecked"
      t.string "builds_are_not_left_broken", null: false, default: "unchecked"
      t.string "orchestrated_deployments", null: false, default: "unchecked"
      t.string "blue_green_deployments", null: false, default: "unchecked"
      t.string "zero_touch_continuous_deployments", null: false, default: "unchecked"
      t.string "infrequent_and_unreliable_releases", null: false, default: "unchecked"
      t.string "manual_process", null: false, default: "unchecked"
      t.string "painful_infrequent_but_reliable_releases", null: false, default: "unchecked"
      t.string "infrequent_but_fully_automated_and_reliable_releases_in_any_environment", null: false, default: "unchecked"
      t.string "frequent_fully_automated_releases", null: false, default: "unchecked"
      t.string "deployment_disconnected_from_release", null: false, default: "unchecked"
      t.string "canary_releases", null: false, default: "unchecked"
      t.string "no_rollbacks_always_roll_forward", null: false, default: "unchecked"
      t.string "data_migrations_are_performed_manually_no_scripts", null: false, default: "unchecked"
      t.string "data_migrations_using_versioned_scripts_performed_manually", null: false, default: "unchecked"
      t.string "automated_and_versioned_changes_to_datastores", null: false, default: "unchecked"
      t.string "changes_to_datastores_automatically_performed_as_part_of_the_deployment_process", null: false, default: "unchecked"
      t.string "automatic_datastore_changes_and_rollbacks_tested_with_every_deployment", null: false, default: "unchecked"
      t.string "automated_unit_tests", null: false, default: "unchecked"
      t.string "separate_test_environment", null: false, default: "unchecked"
      t.string "automatic_integration_tests", null: false, default: "unchecked"
      t.string "static_code_analysis", null: false, default: "unchecked"
      t.string "test_coverage_analysis", null: false, default: "unchecked"
      t.string "automatic_functional_tests", null: false, default: "unchecked"
      t.string "manual_performance_security_tests", null: false, default: "unchecked"
      t.string "fully_automatic_acceptance", null: false, default: "unchecked"
      t.string "automatic_performance_security_tests", null: false, default: "unchecked"
      t.string "manual_exploratory_testing_based_on_risk_based_testing_analysis", null: false, default: "unchecked"
      t.string "verify_expected_business_value", null: false, default: "unchecked"
      t.string "defects_found_and_fixed_immediately_roll_forward", null: false, default: "unchecked"
      t.string "baseline_process_metrics", null: false, default: "unchecked"
      t.string "manual_reporting", null: false, default: "unchecked"
      t.string "visible_to_report_runner", null: false, default: "unchecked"
      t.string "measure_the_process", null: false, default: "unchecked"
      t.string "automatic_reporting", null: false, default: "unchecked"
      t.string "visible_to_team", null: false, default: "unchecked"
      t.string "automatic_generation_of_release_notes", null: false, default: "unchecked"
      t.string "pipeline_traceability", null: false, default: "unchecked"
      t.string "reporting_history", null: false, default: "unchecked"
      t.string "visible_to_cross_silo", null: false, default: "unchecked"
      t.string "report_trend_analysis", null: false, default: "unchecked"
      t.string "real_time_graphs_on_deployment_pipeline_metrics", null: false, default: "unchecked"
      t.string "dynamic_self_service_of_information", null: false, default: "unchecked"
      t.string "customizable_dashboards", null: false, default: "unchecked"
      t.string "cross_reference_across_organizational_boundaries", null: false, default: "unchecked"

      t.index ["form_key"], name: "index_evaluation_form_key"
    end
  end
end
